import canonicalLaneMathlib.AdmissibleClass
import NeuralNetworksBiologicalStudiesArtificialTheoremCanonicalLaneLean.SynapticConnectivity
import NeuralNetworksBiologicalStudiesArtificialTheoremCanonicalLaneLean.SpikeTimingPlasticity
import NeuralNetworksBiologicalStudiesArtificialTheoremCanonicalLaneLean.NeuralNetworkArchitecture
import NeuralNetworksBiologicalStudiesArtificialTheoremCanonicalLaneLean.LearningDynamics

namespace HautevilleHouse
namespace NeuralNetworksBiologicalStudiesArtificialTheoremCanonicalLaneLean

def ConstrainedNeuralNetworksClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_neural_networks_endgame (A : AdmissibleClass) :
    ConstrainedNeuralNetworksClosure A :=
  And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end NeuralNetworksBiologicalStudiesArtificialTheoremCanonicalLaneLean
end HautevilleHouse
